name: Linux

on:
  push:
    branches:
      - develop
      - main

env:
  SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
  SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Send Slack notification
        uses: codedsolar/slack-action@v1
        if: ${{ github.event_name != 'pull_request' }}
        id: slack
        with:
          status: in-progress
      - name: Set ownership to current user
        run: sudo chown -R "$(id -u):$(id -g)" .
      - name: Set up Python 2.7
        uses: actions/setup-python@v4
        with:
          python-version: 2.7
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            g++ \
            libmagick++-dev \
            libmagickcore-dev \
            make \
            pkg-config \
            premake4 \
            tree \
            unzip \
            wget
          python2.7 -m pip install --upgrade pip
          python2.7 -m pip install pillow
      - name: Install ktools
        run: |
          wget https://github.com/dstmodders/ktools/archive/refs/tags/v4.4.1.tar.gz
          tar xf v4.4.1.tar.gz
          cd ./ktools-4.4.1/
          cmake \
            -DImageMagick_Magick++_LIBRARY="$(pkg-config --variable=libdir Magick++)/lib$(pkg-config --variable=libname Magick++).so" \
            -DImageMagick_MagickCore_INCLUDE_DIR="$(pkg-config --cflags-only-I MagickCore | tail -c+3)" \
            -DImageMagick_MagickCore_LIBRARY="$(pkg-config --variable=libdir MagickCore)/lib$(pkg-config --variable=libname MagickCore).so" \
            -DImageMagick_MagickWand_INCLUDE_DIR="$(pkg-config --cflags-only-I MagickWand | tail -c+3)" \
            -DImageMagick_MagickWand_LIBRARY="$(pkg-config --variable=libdir MagickWand)/lib$(pkg-config --variable=libname MagickWand).so" \
          .
          ./configure
          make
          make install
      - name: Run premake
        working-directory: ./src/
        run: ./premake.sh
      - name: Build
        working-directory: ./build/proj/
        run: make config=release
      - name: Display build directory tree
        run: tree ./build/
      - name: Run autocompiler
        working-directory: ./build/linux/mod_tools/
        run: ./autocompiler
      - name: Upload mods output
        uses: actions/upload-artifact@v3
        with:
          name: linux-test-mods
          path: build/dont_starve/mods/
      - name: Update Slack notification
        uses: codedsolar/slack-action@v1
        if: ${{ github.event_name != 'pull_request' && always() }}
        with:
          status: ${{ job.status }}
          timestamp: ${{ steps.slack.outputs.slack-timestamp }}
