name: Windows

on:
  push:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set a job-wide environment variables
        shell: powershell
        run: |
          echo ("BRANCH_NAME=" + $env:GITHUB_REF.replace('refs/heads/', '')) >> $env:GITHUB_ENV
          echo "GITHUB_JOB_NAME=build" >> $env:GITHUB_ENV
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.3
      - name: Run premake
        working-directory: ./src/
        shell: powershell
        run: ./premake.bat
      - name: Build
        working-directory: ./build/proj/
        shell: powershell
        run: msbuild mod_tools.sln /p:Configuration=release /p:PlatformToolset=v142
      - name: Display build directory tree
        shell: powershell
        working-directory: ./build/
        run: tree /f /a
      - name: Run autocompiler
        working-directory: ./build/win32/mod_tools/
        shell: powershell
        run: ./autocompiler.exe
      - name: Upload mods output
        uses: actions/upload-artifact@v2
        with:
          name: windows-test-mods
          path: build/dont_starve/mods/
      - name: Prepare success Slack notification
        if: success()
        shell: powershell
        run: echo "SLACK_CUSTOM_PAYLOAD=$env:SLACK_CUSTOM_PAYLOAD" >> $env:GITHUB_ENV
        env:
          SLACK_CUSTOM_PAYLOAD: '{"channel":"${{ secrets.SLACK_CHANNEL }}","attachments":[{"color":"#2eb886","fallback":"GitHub Actions {{ GITHUB_WORKFLOW }} workflow {{ GITHUB_JOB_NAME }} job of {{ GITHUB_REPOSITORY }}@{{ BRANCH_NAME }} by {{ GITHUB_ACTOR }} has passed","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"GitHub Actions *<https://github.com/{{ GITHUB_REPOSITORY }}/actions/runs/{{ GITHUB_RUN_ID }}|{{ GITHUB_WORKFLOW }}>* workflow *{{ GITHUB_JOB_NAME }}* job of *<https://github.com/{{ GITHUB_REPOSITORY }}|{{ GITHUB_REPOSITORY }}>@<https://github.com/{{ GITHUB_REPOSITORY }}/tree/{{ BRANCH_NAME }}|{{ BRANCH_NAME }}>* by *{{ GITHUB_ACTOR }}* has passed"}}]}]}'
      - name: Prepare failure Slack notification
        if: failure()
        shell: powershell
        run: echo "SLACK_CUSTOM_PAYLOAD=$env:SLACK_CUSTOM_PAYLOAD" >> $env:GITHUB_ENV
        env:
          SLACK_CUSTOM_PAYLOAD: '{"channel":"${{ secrets.SLACK_CHANNEL }}","attachments":[{"color":"#ed2f00","fallback":"GitHub Actions {{ GITHUB_WORKFLOW }} workflow {{ GITHUB_JOB_NAME }} job of {{ GITHUB_REPOSITORY }}@{{ BRANCH_NAME }} by {{ GITHUB_ACTOR }} has failed","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"GitHub Actions *<https://github.com/{{ GITHUB_REPOSITORY }}/actions/runs/{{ GITHUB_RUN_ID }}|{{ GITHUB_WORKFLOW }}>* workflow *{{ GITHUB_JOB_NAME }}* job of *<https://github.com/{{ GITHUB_REPOSITORY }}|{{ GITHUB_REPOSITORY }}>@<https://github.com/{{ GITHUB_REPOSITORY }}/tree/{{ BRANCH_NAME }}|{{ BRANCH_NAME }}>* by *{{ GITHUB_ACTOR }}* has failed"}}]}]}'
      - name: Send Slack notification
        if: ${{ !env.ACT && always() }}
        uses: Ilshidur/action-slack@2.1.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
